### ISSUE TITLE
Add URL config option to app

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [PredictiveEcology/wbi_shiny#15]
We want the ability to specify the exact URL path to the app; look into how to do this via {golem}

**Comment by psolymos** [comment]
Use `onLoad()` in `app/R/zzz.R` to set global package options. Then we can use `getOption()` in the package to access the base URL value and `options()` to reset it to any new value.

```R
# R/zzz.R
.onLoad <- function(libname, pkgname) {
    if (is.null(getOption("ShinyWBI"))) {
        options("ShinyWBI" = list(
            baseurl = "https://example.com", 
            version = "v1"
        ))
    }
    invisible(NULL)
}

.onUnload <- function(libpath) {
    if (options_set) {
        options("ShinyWBI" = NULL)
    }
    invisible(NULL)
}
```

**Comment by psolymos** [comment]
Decided to use `golem-config.yml` and `get_golem_config()`.
