### ISSUE TITLE
minor typo on "apps" tab

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/wbi_shiny#20]
See https://wbi-nwt.analythium.app/apps.html

![image](https://user-images.githubusercontent.com/3435577/165172738-75e1dbf9-aa47-40f7-9136-7b72b24f7ce1.png)

I think it should be "Web applications"

**Comment by psolymos** [comment]
I invented the term 'applocation' referring to spatial applications (app + location) in the hopes that it will catch on :)

I will change it to a more traditional 'application'...

Any suggestions for a nice thumbnail for the app?
