### ISSUE TITLE
`absolutePanel` taking up too much space

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [PredictiveEcology/wbi_shiny#24]
On the **Map** and **Side-by-Side** pages, the floating `absolutePanel` (containing the filter widgets) is crowding up quite a bit of space on screen, especially given that we will be adding an additional filter option for *"Region"*.

Instead, we can move the filter widgets into a `modalDialog` that is launched using an `actionButton` in the `absolutePanel`.  Additionally, we can provide summary information in the `absolutePanel` on the selected choices the user is seeing (which were set in the `modalDialog`.

**Comment by psolymos** [comment]
@mthomas-ketchbrook I like the idea of a simplified `absolutePanel` that triggers a modal where a lot more options can be set.

For the side by side comparison, we want:

- radio button or similar to switch between "compare time periods" vs "compare scenarios"
- region (full extent as default) and element (default same as the landing page) should be fixed for the comparison, selectable from dropdowns
- depending on periods/scenario setting, 2 dropdowns to select the 2 periods/scenarios to compare

Adding this information to the panel or modal, e.g. "Comparing periods 2011 and 2100 under scenario XXX" would be useful. Thanks!

**Comment by mthomas-ketchbrook** [comment]
@psolymos I have most of the technical pieces of this ironed out now on the **"Map"** page [here](https://github.com/PredictiveEcology/wbi_shiny/blob/24-absolutepanel-taking-up-too-much-space/03-apps/wbi/R/mod_map.R).  I also leveraged the Bootstrap accordion to make the `absolutePanel` collapsible.  It's a [little hacky](https://github.com/PredictiveEcology/wbi_shiny/blob/24-absolutepanel-taking-up-too-much-space/03-apps/wbi/R/utils_inputs.R#L16-L36) for now, but I'll clean it up soon.

https://user-images.githubusercontent.com/52801195/236018256-083dd0a3-9ca8-40b8-8ad7-d90aac963e4d.mp4

Let me know your thoughts and I can bring it over to the **"Side-by-Side"** page and start incorporating Region and the items you bulleted above.

**Comment by psolymos** [comment]
I like this new setup. It gives the info, you can minimize it, and it provides enough space to include more complex selectors. This can really help with the mobile view where the absolutePanel was really getting in the way of the view.

Keep it modular so that it is easy to tweak/style later. Thanks!

**Comment by mthomas-ketchbrook** [comment]
FYI -- {bslib} development version on GitHub has a function called `accordion()` that will likely be available in the next CRAN release.  Thus, in the future we may not need the custom function (since we are already importing {bslib} elsewhere.

https://rstudio.github.io/bslib/reference/accordion.html

**Comment by psolymos** [comment]
The model based approach implemented in #25 closes this issue.
