### ISSUE TITLE
Downloads to display message

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#26]
The functionality needed to "future-proof" the download table:

- a download button in each row instead of a direct link
- clicking the button shows a message (alert, but preferably a modal)
- the modal should have the following info based on columns in the table referencing each row (that the button is for):
  - `$downloadable=T/F`: can you download or not, display a download button or clickable link when TRUE
  - custom HTML text to display (citation information, caveats, etc.), this would get displayed above the download button
  - a close button (i.e. when not downloadable, get rid of the modal)

**Comment by psolymos** [comment]
Some links to examples:

- <https://glin.github.io/reactable/articles/examples.html#custom-action>
- <https://discindo.org/post/reactable-buttons/>

**Comment by mthomas-ketchbrook** [comment]
UI mock-up for "Download" page, based upon 2023-05-23 meeting between @psolymos & myself:

![image](https://github.com/PredictiveEcology/wbi_shiny/assets/52801195/770cd463-e4fc-4e61-b7e0-eee43e8f9d08)

**Comment by mthomas-ketchbrook** [comment]
2023-05-30: @psolymos will re-run the .csv data to add 2 new columns (`show = T/F` and `note = <HTML string>`)

**Comment by mthomas-ketchbrook** [comment]
Closed 222fde1a174744edf27167b7709f8bbff601d47d
