### ISSUE TITLE
Maps turning all red

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#30]
There has been some cases, when the maps (full extent or regional) look all red. For example:

```R
r=rast("https://wbi.predictiveecology.org/api/v1/public/wbi/full-extent/elements/bird-alfl/canesm5-ssp370/2011/lonlat/mean.tif")
```
![image](https://github.com/PredictiveEcology/wbi_shiny/assets/831636/b3c6a7c0-e929-4f0e-b9a1-0886bea6210b)

The reason this happens is due to the min value for the map domain/palette being fixed at 0. When min > 0 for wide ranging species and min is close to max (like here 0.114 -- 0.124), the 0 -- min breaks take up all the non-red colors (min is >90% of max).

Values look similar at the raw 250 m level, e.g.:

```R
r1=rast("https://wbi.predictiveecology.org/api/v1/public/wbi/ab/elements/bird-alfl/canesm5-ssp370/2011/250m/mean.tif")
```

![image](https://github.com/PredictiveEcology/wbi_shiny/assets/831636/8b7b6e8e-3b33-4c06-ae85-be2b3dd6838e)

Therefore it is not a processing error but a consequence of the predicted values.

**Proposed solution: relax map palette min = 0 rule.**

**Comment by mthomas-ketchbrook** [comment]
2023-05-30:  Use a global {golem} config YAML option `app_use_min` (default is `yes`) to set whether zero should be the minimum legend value (`FALSE`) or whether the minimum value from the data (per group) should be used (`TRUE`, column `q0`).
