### ISSUE TITLE
Regional summaries

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#5]
1. Identify boundary files (shp, gdb) to be used
2. Summarize elements/periods/treatments in units
3. Organize summaries
4. Store (file, DB)

If we decide to store results in files, we can add those to the API as JSON text. This should work if data not extensive.

**Comment by psolymos** [comment]
@mthomas-ketchbrook nice progress on the summaries! Would it make sense to show the chart as the default and have the table view as secondary?

**Comment by mthomas-ketchbrook** [comment]
> @mthomas-ketchbrook nice progress on the summaries! Would it make sense to show the chart as the default and have the table view as secondary?

All set!  f57f075733c965d4ad1de2a3052f22c1bb2e5a2e
