### ISSUE TITLE
Assets browser

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#6]
Assets browser will provide a sortable/filterable table (DT, reactable, etc). The purpose is to allow users to explore the files (and other assets) available for download, and provide a link (e.g. copy to clipboard). It will pull info from the API metadata.

[Here](https://github.com/psolymos/bSims/blob/master/inst/shiny/bsimsH.R) is a simple JS based solution for the copy-to-clipboard functionality.

**Comment by mthomas-ketchbrook** [comment]
> * [x]  Use dropdowns in the table instead of the filter fields   <- a9985d76d311e722624a1aa0c07adae4bdbd82f6
> * [ ]  Add tooltips (this applies in general, see example [here](https://github.com/psolymos/moosecounter/blob/main/inst/shiny/www/tips.js))
> * [x]  Use plain language instead of developer terms (Assets-->Downloads, Period-->Time period, Element-->Species)   <- 2acfcc7cc57a80c1aaea84c88600a677033c82fa

@psolymos , do you still want to add tooltips?  If so, just on the "Downloads" page, or throughout the app?  Can you be more specific?

**Comment by psolymos** [comment]
@mthomas-ketchbrook at the very end, yes. I'll start a new issue for docs. Thanks!
